---

- name: Spin up a clean EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - provision_ec2

- name: SSH into the instance and install required updates
  hosts: server
  connection: ssh
  remote_user: centos
  become: yes
  gather_facts: False
  roles:
    - system_updates

- name: Install dependencies
  hosts: server
  connection: ssh
  remote_user: centos
  gather_facts: False
  roles:
    - goss
    - git
    - gcc-c++
    - make
    - nodejs
    - python3
    - java8
    - golang
    - clean_up
