---

- name: Copy template files to host
  become: yes
  template:
    src: "{{ test_name }}.j2"
    dest: "{{ goss_templates_dir }}/{{ test_name }}.yaml"
    mode: 0644

- name: Run goss tests
  become: yes
  goss:
    path: "{{ goss_templates_dir }}/{{ test_name }}.yaml"
    format: documentation
    output_file: "{{ goss_test_results_dir }}/{{ test_name }}.xml"
  ignore_errors: yes #switch to no
  register: goss_output

- name: Retrieve test results
  fetch:
    src: "{{ goss_test_results_dir }}/{{ test_name }}.xml"
    dest: "tests/{{ test_name }}.xml"
    flat: yes

- name: Manually fail on error
  fail:
    msg: "Goss test failed: Check {{ test_name }}.yaml"
  when: goss_output.failed is defined and goss_output.failed == true

- name: Debug goss_output
  debug:
    msg: "{{ goss_output.stdout_lines }}"
